name = "startresume-io"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[env.production.vars]
NODE_ENV = "production"

# Environment variables will be set in Cloudflare Pages dashboard
# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = ""
# CLERK_SECRET_KEY = ""
# OPENAI_API_KEY = ""
# STRIPE_SECRET_KEY = ""
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = ""
# STRIPE_WEBHOOK_SECRET = ""
# NEXT_PUBLIC_SUPABASE_URL = ""
# NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
# SUPABASE_SERVICE_ROLE_KEY = ""
# NEXT_PUBLIC_APP_URL = ""
